apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: step-eks-cluster
  region: eu-west-1

vpc:
  id: "vpc-06754e5c4b099e503"
  cidr: "172.31.0.0/16"
  subnets:
    public:
      eu-west-1c: { id: subnet-0b96c674edf7a8efe }
      eu-west-1a: { id: subnet-096aff736380c56fd }
      eu-west-1b: { id: subnet-04b8a8330fd7d7919 }

managedNodeGroups:
  - name: ng-db
    instanceType: t3.small
    labels: { role: builders }
    minSize: 2
    maxSize: 4
    tags:
      Name: ng-db
  - name: ng-spot
    instanceType: t3.medium
    labels: { role: builders }
    minSize: 3
    maxSize: 6
    spot: true
    tags:
      Name: ng-spot
